export const FETCH_ACCESS_TOKEN = 'FETCH_ACCESS_TOKEN';
export const CREATE_USER = 'CREATE_USER';
export const LOGOUT = 'LOGOUT';
export const LOGIN_ATTEMPTED = 'LOGIN_ATTEMPTED'
export const REGISTRATION_ATTEMPTED = 'REGISTRATION_ATTEMPTED'
export const FETCH_SPOTIFY_TOKENS = 'FETCH_SPOTIFY_TOKENS'
export const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN';
